import type { HaEntity } from '../../../api/homeAssistant';

export const HOME_ASSISTANT_PREVIEW: HaEntity[] = [
  {
    id: 'light.desk_lamp',
    name: 'Desk Lamp',
    domain: 'light',
    state: 'on',
    on: true,
    reachable: true,
    brightnessPct: 80,
    supportsBrightness: true,
    supportsColor: true,
    supportsColorTemp: false,
    rgb: [255, 200, 100],
    colorTempK: 0,
    area: 'Office',
  },
  {
    id: 'light.ceiling',
    name: 'Ceiling',
    domain: 'light',
    state: 'off',
    on: false,
    reachable: true,
    brightnessPct: 0,
    supportsBrightness: true,
    supportsColor: false,
    supportsColorTemp: true,
    rgb: null,
    colorTempK: 4000,
    area: 'Office',
  },
  {
    id: 'switch.fan',
    name: 'Fan',
    domain: 'switch',
    state: 'on',
    on: true,
    reachable: true,
    brightnessPct: 0,
    supportsBrightness: false,
    supportsColor: false,
    supportsColorTemp: false,
    rgb: null,
    colorTempK: 0,
    area: 'Office',
  },
  {
    id: 'light.sofa_lamp',
    name: 'Sofa Lamp',
    domain: 'light',
    state: 'on',
    on: true,
    reachable: true,
    brightnessPct: 45,
    supportsBrightness: true,
    supportsColor: true,
    supportsColorTemp: false,
    rgb: [200, 150, 255],
    colorTempK: 0,
    area: 'Living Room',
  },
  {
    id: 'switch.tv',
    name: 'TV',
    domain: 'switch',
    state: 'on',
    on: true,
    reachable: true,
    brightnessPct: 0,
    supportsBrightness: false,
    supportsColor: false,
    supportsColorTemp: false,
    rgb: null,
    colorTempK: 0,
    area: 'Living Room',
  },
  {
    id: 'switch.hallway_motion',
    name: 'Hallway Motion',
    domain: 'switch',
    state: 'off',
    on: false,
    reachable: true,
    brightnessPct: 0,
    supportsBrightness: false,
    supportsColor: false,
    supportsColorTemp: false,
    rgb: null,
    colorTempK: 0,
    area: '',
  },
];
